### ISSUE TITLE
neovimがインストールできない

### ISSUE THREAD

**Issue by Sakurai00** [Sakurai00/dotfiles#125]
![image](https://user-images.githubusercontent.com/54164011/224551487-d51bba4b-3440-4b41-89f8-fd48de01fcdd.png)

https://github.com/neovim/neovim/wiki/Installing-Neovim

**Comment by Sakurai00** [comment]
```
- name: Add neovim repository
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable

- name: Install neovim
  become: yes
  ansible.builtin.apt:
    name:
      - vim
      - neovim
    update_cache: yes
```
これだと動かなかった．依存関係が解決できないっぽい．

```
- name: Install neovim
  become: yes
  ansible.builtin.apt:
    deb: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb
```
これならいけた
